/**
 * One-off: link the existing "Iphone, Cetelam" transactions to a new installment
 * plan. Generates SQL only — nothing runs against a database from this script.
 *
 * The generated SQL is deliberately conservative:
 *   - It only ever touches rows that are still unlinked (`plan_id IS NULL`),
 *     match the exact description, and match the per-installment amount, so a
 *     re-run or a wrong count cannot corrupt other data.
 *   - Installment indices are assigned by chronological budget month via a
 *     window function starting at START_INDEX, so no transaction id is hardcoded.
 *
 * Recommended flow (roy-expenses = prod; use roy-expenses-stg to rehearse):
 *   1. Apply the migration first:
 *        npx wrangler d1 execute roy-expenses --remote --file=migrations/0009_installment_plans.sql
 *   2. Generate the SQL:
 *        EXPENSE_OWNER=you@example.com npx tsx scripts/link-iphone-installments.ts /tmp/link-iphone.sql
 *   3. DRY RUN — inspect what will be linked (should return the expected count/rows):
 *        npx wrangler d1 execute roy-expenses --remote --command \
 *          "SELECT id, date, budget_month, amount_cents FROM transactions \
 *           WHERE owner='you@example.com' AND description='Iphone, Cetelam' \
 *           AND amount_cents=5783 AND plan_id IS NULL ORDER BY budget_month, date, id;"
 *   4. Apply:
 *        npx wrangler d1 execute roy-expenses --remote --file=/tmp/link-iphone.sql
 *   5. Verify (indices 14..20, plan populated):
 *        npx wrangler d1 execute roy-expenses --remote --command \
 *          "SELECT installment_index, budget_month FROM transactions \
 *           WHERE owner='you@example.com' AND plan_id IS NOT NULL ORDER BY installment_index;"
 *   6. Delete this script once the link is confirmed.
 */
import { writeFileSync } from 'node:fs'

const OWNER = process.env.EXPENSE_OWNER?.trim().toLowerCase()
if (!OWNER) throw new Error('Set EXPENSE_OWNER to the Cloudflare Access email')

const DESCRIPTION = process.env.PLAN_DESCRIPTION ?? 'Iphone, Cetelam'
const AMOUNT_CENTS = Number(process.env.PLAN_AMOUNT_CENTS ?? 5783)
const TOTAL_COUNT = Number(process.env.PLAN_TOTAL_COUNT ?? 24)
const ANCHOR_MONTH = process.env.PLAN_ANCHOR_MONTH ?? '2026-01'
const START_INDEX = Number(process.env.PLAN_START_INDEX ?? 14)
const ACCOUNT_ID = Number(process.env.PLAN_ACCOUNT_ID ?? 0)
const CATEGORY_ID = Number(process.env.PLAN_CATEGORY_ID ?? 0)

if (!ACCOUNT_ID || !CATEGORY_ID) {
  throw new Error('Set PLAN_ACCOUNT_ID and PLAN_CATEGORY_ID (look them up in the accounts/categories tables)')
}

const str = (v: string): string => `'${v.replace(/'/g, "''")}'`
const owner = str(OWNER)
const desc = str(DESCRIPTION)

const sql = `-- Generated by scripts/link-iphone-installments.ts. Review before applying.

INSERT INTO installment_plans
  (owner, description, total_count, amount_cents, account_id, category_id, type,
   anchor_budget_month, start_installment_index, active)
VALUES
  (${owner}, ${desc}, ${TOTAL_COUNT}, ${AMOUNT_CENTS}, ${ACCOUNT_ID}, ${CATEGORY_ID}, 'expense',
   ${str(ANCHOR_MONTH)}, ${START_INDEX}, 1);

WITH ordered AS (
  SELECT id,
         (ROW_NUMBER() OVER (ORDER BY budget_month, date, id) - 1 + ${START_INDEX}) AS idx
  FROM transactions
  WHERE owner = ${owner}
    AND description = ${desc}
    AND amount_cents = ${AMOUNT_CENTS}
    AND plan_id IS NULL
)
UPDATE transactions
SET plan_id = (SELECT id FROM installment_plans WHERE owner = ${owner} AND description = ${desc}),
    installment_index = (SELECT idx FROM ordered WHERE ordered.id = transactions.id)
WHERE id IN (SELECT id FROM ordered);
`

const out = process.argv[2] ?? '/tmp/link-iphone.sql'
writeFileSync(out, sql)
process.stderr.write(`Wrote linking SQL to ${out}\n`)
